import localFont from "next/font/local";
import { Analytics } from "@vercel/analytics/react"
import "./globals.css";
import Navbar from "./Layout/Navbar";
import Footer from "./Layout/Footer";
import NextTopLoader from "nextjs-toploader";

const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata = {
    title: "CARINIME",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <>
            <html lang="en">
                <head>
                    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                    <link rel="shortcut icon" href={"/icon.png"} type="image/x-icon" />
                </head>
                <body className={`${geistMono.variable}`}>
                    <NextTopLoader color="#2299DD"
                        initialPosition={0.08}
                        crawlSpeed={200}
                        height={3}
                        crawl={true}
                        showSpinner={false}
                        easing="ease"
                        speed={200}
                        shadow="0 0 10px #2299DD,0 0 5px #2299DD" />
                    <Navbar />
                    <main>
                        {children}
                    </main>
                    <Analytics />
                    <Footer />
                </body>
            </html>
        </>
    );
}
