import localFont from "next/font/local";
import { Analytics } from "@vercel/analytics/react"
import "./globals.css";
import Navbar from "./Layout/Navbar";
import Footer from "./Layout/Footer";

const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata = {
    title: "CARINIME",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <>
            <html lang="en">
                <head>
                    <link rel="shortcut icon" href={"/icon.png"} type="image/x-icon" />
                </head>
                <body className={`${geistMono.variable}`}>
                    <Navbar />
                    {children}
                    <Analytics />
                    <Footer />
                </body>
            </html>
        </>
    );
}
